#!/usr/bin/env python3
"""kiro2claude: run a project's Kiro AI workflow (.kiro/) in Claude Code.

https://github.com/karawanshy/kiro2claude · MIT License

.kiro/ stays the single source of truth. This tool translates it into the
files Claude Code reads (CLAUDE.md, .claude/agents, .claude/skills,
.claude/rules, .mcp.json). Every file it writes is generated, gitignored and
recorded in a manifest, so it can be rebuilt or removed at any time and it
never overwrites a file it did not create.

Kiro hooks are not translated into settings: a fixed .claude/settings.json
routes every Claude Code hook event to `dispatch`, which reads .kiro/hooks/ at
run time and executes the matching Kiro hooks.

Commands (`kiro2claude` when installed, `python3 kiro2claude.py` when vendored):
  sync [--check] [--force] [--session-start]
      Regenerate when .kiro/ (or this tool) changed since the last run.
      --check          exit 1 if generated files are stale, write nothing
      --force          regenerate even if nothing changed
      --session-start  emit SessionStart hook JSON (used by settings.json)
  dispatch <ClaudeHookEvent>
      Run the Kiro hooks matching a Claude Code hook event (reads the event
      JSON on stdin).
  init [--force]
      Write .claude/settings.json and .gitignore entries, then sync.
  --version

Standard library only (Python 3.9+).
"""

from __future__ import annotations

import fnmatch
import glob as globlib
import hashlib
import json
import os
import re
import shlex
import shutil
import subprocess
import sys
from pathlib import Path

__version__ = "0.1.0"

TOOL = "kiro2claude"
STATE_DIR = ".claude/.kiro2claude"
STATE_FILE = f"{STATE_DIR}/state.json"
GENERATED_NOTE = (
    "Generated by kiro2claude from .kiro/. Do not edit: change .kiro/ instead; "
    "it is regenerated automatically at Claude Code session start."
)

# Inputs whose changes trigger regeneration (relative to .kiro/).
HASHED_KIRO_DIRS = ("agents", "skills", "steering", "hooks", "settings")

# Claude Code built-in commands/skills a Kiro skill must not shadow.
RESERVED_SKILL_NAMES = {
    "agents", "batch", "claude-api", "clear", "code-review", "compact",
    "config", "context", "cost", "doctor", "fewer-permission-prompts", "help",
    "hooks", "init", "keybindings-help", "login", "logout", "loop", "mcp",
    "memory", "model", "permissions", "pr-comments", "resume", "review", "run",
    "schedule", "security-review", "simplify", "status", "statusline",
    "update-config",
}
RENAMED_SKILL_PREFIX = "kiro-"

# Kiro agent tool -> Claude Code tools. None = grant all tools (omit `tools`).
KIRO_TOOLS_TO_CLAUDE = {
    "read": ["Read", "Grep", "Glob"],
    "fs_read": ["Read", "Grep", "Glob"],
    "grep": ["Grep"],
    "glob": ["Glob"],
    "write": ["Edit", "Write", "NotebookEdit"],
    "fs_write": ["Edit", "Write", "NotebookEdit"],
    "shell": ["Bash"],
    "execute_bash": ["Bash"],
    "execute_cmd": ["Bash"],
    "subagent": ["Agent"],
    "use_subagent": ["Agent"],
    "delegate": ["Agent"],
    "todo_list": ["TodoWrite"],
    "web_search": ["WebSearch"],
    "web_fetch": ["WebFetch"],
    "thinking": [],
    "*": None,
    "@builtin": None,
    "@mcp": None,  # Claude Code lists MCP tools by name; inheriting is the only equivalent
}
COORDINATOR_TOOLS = {"subagent", "use_subagent", "delegate"}

# Claude Code tool -> the Kiro names a Kiro hook matcher may use for it.
_WRITE_ALIASES = {"fs_write", "write"}
CLAUDE_TOOL_TO_KIRO = {
    "Bash": {"execute_bash", "execute_cmd", "shell"},
    "Read": {"fs_read", "read"},
    "Grep": {"fs_read", "read", "grep"},
    "Glob": {"fs_read", "read", "glob"},
    "Edit": _WRITE_ALIASES,
    "Write": _WRITE_ALIASES,
    "MultiEdit": _WRITE_ALIASES,
    "NotebookEdit": _WRITE_ALIASES,
    "WebFetch": {"web_fetch", "web"},
    "WebSearch": {"web_search", "web"},
    "Agent": {"use_subagent", "subagent", "delegate"},
    "Task": {"use_subagent", "subagent", "delegate"},
    "TodoWrite": {"todo_list"},
}
FILE_WRITE_TOOLS = {"Edit", "Write", "MultiEdit", "NotebookEdit"}

# Kiro hook trigger (normalized) -> Claude Code hook event.
KIRO_TRIGGER_TO_CLAUDE = {
    "pretooluse": "PreToolUse",
    "posttooluse": "PostToolUse",
    "promptsubmit": "UserPromptSubmit",
    "userpromptsubmit": "UserPromptSubmit",
    "agentstop": "Stop",
    "stop": "Stop",
    "agentspawn": "SessionStart",
    "sessionstart": "SessionStart",
    "fileedited": "PostToolUse",
    "filesaved": "PostToolUse",
    "filecreated": "PostToolUse",
}
FILE_TRIGGERS = {"fileedited", "filesaved", "filecreated"}

# Events the fixed settings.json routes to `dispatch`, with hook timeouts (s).
DISPATCHED_EVENTS = {
    "SessionStart": 120,
    "UserPromptSubmit": 120,
    "PreToolUse": 600,
    "PostToolUse": 600,
    "Stop": 600,
}

GITIGNORE_BLOCK = """\
# kiro2claude: generated from .kiro/ (do not commit)
/CLAUDE.md
/.mcp.json
/.claude/agents/
/.claude/skills/
/.claude/rules/
/.claude/.kiro2claude/
"""


# --------------------------------------------------------------------------
# Small helpers
# --------------------------------------------------------------------------

def find_root() -> Path:
    env = os.environ.get("CLAUDE_PROJECT_DIR")
    if env and (Path(env) / ".kiro").is_dir():
        return Path(env).resolve()
    here = Path.cwd().resolve()
    for p in (here, *here.parents):
        if (p / ".kiro").is_dir():
            return p
    raise SystemExit(f"{TOOL}: no .kiro/ directory found from {here}")


def norm(s: str) -> str:
    return re.sub(r"[^a-z0-9]", "", s.lower())


def yaml_str(s: str) -> str:
    # A JSON string is a valid YAML double-quoted scalar.
    return json.dumps(s, ensure_ascii=False)


def _scalar(v: str):
    v = v.strip()
    if len(v) >= 2 and v[0] == v[-1] and v[0] in "'\"":
        return v[1:-1]
    if v.startswith("[") and v.endswith("]"):
        return [_scalar(x) for x in v[1:-1].split(",") if x.strip()]
    if v.lower() in ("true", "false"):
        return v.lower() == "true"
    return v


def split_frontmatter(text: str):
    """Return (meta, body) for a Markdown file with optional --- frontmatter.

    Supports the flat subset steering/skill files use: `key: value`, inline
    `[a, b]` lists and `- item` lists.
    """
    lines = text.splitlines(keepends=True)
    if not lines or lines[0].strip() != "---":
        return {}, text
    for i in range(1, len(lines)):
        if lines[i].strip() == "---":
            meta, key = {}, None
            for raw in lines[1:i]:
                line = raw.rstrip("\n")
                if not line.strip() or line.lstrip().startswith("#"):
                    continue
                item = re.match(r"^\s+-\s+(.*)$", line) or re.match(r"^-\s+(.*)$", line)
                if item and key:
                    if not isinstance(meta.get(key), list):
                        meta[key] = []
                    meta[key].append(_scalar(item.group(1)))
                    continue
                kv = re.match(r"^([A-Za-z0-9_-]+)\s*:\s*(.*)$", line)
                if kv:
                    key = kv.group(1)
                    meta[key] = _scalar(kv.group(2)) if kv.group(2).strip() else []
            return meta, "".join(lines[i + 1:])
    return {}, text


def first_sentence(text: str, limit: int = 220) -> str:
    text = " ".join(text.split())
    m = re.match(r"^(.+?[.!?])(\s|$)", text)
    s = m.group(1) if m else text
    return s if len(s) <= limit else s[: limit - 1].rstrip() + "…"


def rel(path: Path, root: Path) -> str:
    return path.relative_to(root).as_posix()


# --------------------------------------------------------------------------
# Reading .kiro/
# --------------------------------------------------------------------------

def compute_hash(root: Path) -> str:
    h = hashlib.sha256()
    h.update(Path(__file__).read_bytes())  # regenerate when the tool changes
    kiro = root / ".kiro"
    for sub in HASHED_KIRO_DIRS:
        base = kiro / sub
        if not base.exists():
            continue
        for p in sorted(base.rglob("*")):
            if p.is_file():
                h.update(rel(p, root).encode() + b"\0")
                h.update(p.read_bytes() + b"\0")
    specs = kiro / "specs"
    if specs.is_dir():  # spec file names appear in CLAUDE.md, contents do not
        for p in sorted(specs.rglob("*.md")):
            h.update(rel(p, root).encode() + b"\0")
    # Where CLAUDE.md goes depends on whether a hand-written one exists.
    h.update(b"claude_md_unmanaged" if claude_md_is_unmanaged(root) else b"")
    return h.hexdigest()


def load_state(root: Path) -> dict:
    try:
        return json.loads((root / STATE_FILE).read_text())
    except (OSError, ValueError):
        return {}


def claude_md_is_unmanaged(root: Path) -> bool:
    p = root / "CLAUDE.md"
    owned = {o["path"] for o in load_state(root).get("outputs", [])}
    return p.exists() and "CLAUDE.md" not in owned


def read_agents(root: Path, warnings: list) -> list:
    agents = []
    for path in sorted((root / ".kiro/agents").glob("*.json")):
        try:
            data = json.loads(path.read_text())
        except ValueError as e:
            warnings.append(f"agent {path.name}: invalid JSON ({e}); skipped")
            continue
        name = data.get("name") or path.stem
        prompt = data.get("prompt") or ""
        if prompt.startswith("file://"):
            ref = (path.parent / prompt[len("file://"):]).resolve()
            try:
                prompt = ref.read_text()
            except OSError:
                warnings.append(f"agent {name}: prompt file {ref} not found")
                prompt = ""
        files, skills = [], []
        for res in data.get("resources") or []:
            if not isinstance(res, str):
                warnings.append(f"agent {name}: unsupported resource {res!r}; skipped")
                continue
            if res.startswith("skill://"):
                skills.append(res[len("skill://"):])
            elif res.startswith("file://"):
                pattern = res[len("file://"):]
                matches = sorted(
                    rel(Path(m).resolve(), root)
                    for m in globlib.glob(str(root / pattern), recursive=True)
                    if Path(m).is_file()
                )
                files.extend(matches or [pattern])
            else:
                warnings.append(f"agent {name}: unsupported resource {res!r}; skipped")
        for key in ("hooks", "toolsSettings", "knowledgeBase"):
            if data.get(key):
                warnings.append(f"agent {name}: `{key}` has no Claude Code equivalent; ignored")
        agents.append({
            "name": name,
            "source": rel(path, root),
            "description": data.get("description") or "",
            "prompt": prompt,
            "tools": data.get("tools") or [],
            "model": data.get("model"),
            "files": files,
            "skills": skills,
        })
    return agents


def read_skills(root: Path) -> list:
    skills = []
    base = root / ".kiro/skills"
    for skill_md in sorted(base.glob("*/SKILL.md")):
        meta, _ = split_frontmatter(skill_md.read_text())
        name = str(meta.get("name") or skill_md.parent.name)
        skills.append({
            "name": name,
            "dir": skill_md.parent,
            "description": str(meta.get("description") or ""),
        })
    return skills


def read_steering(root: Path) -> list:
    out = []
    base = root / ".kiro/steering"
    for path in sorted(base.rglob("*.md")):
        meta, body = split_frontmatter(path.read_text())
        inclusion = norm(str(meta.get("inclusion") or "always"))
        patterns = meta.get("fileMatchPattern") or meta.get("fileMatchPatterns") or []
        if isinstance(patterns, str):
            patterns = [p.strip() for p in patterns.split(",") if p.strip()]
        slug = re.sub(r"[^a-z0-9]+", "-", path.relative_to(base).with_suffix("").as_posix().lower()).strip("-")
        heading = re.search(r"^#\s+(.+)$", body, re.M)
        out.append({
            "path": rel(path, root),
            "slug": slug,
            "inclusion": inclusion,
            "patterns": patterns,
            "description": str(meta.get("description") or (heading.group(1) if heading else slug)),
            "body": body,
            "refs": re.findall(r"#\[\[file:([^\]]+)\]\]", body),
        })
    return out


def read_hooks(root: Path, warnings=None) -> list:
    """Normalize every Kiro hook (v1 JSON and IDE .kiro.hook formats)."""
    hooks = []
    base = root / ".kiro/hooks"
    if not base.is_dir():
        return hooks
    for path in sorted(base.iterdir()):
        if not path.is_file() or not (path.suffix == ".json" or path.name.endswith(".kiro.hook")):
            continue
        try:
            data = json.loads(path.read_text())
        except ValueError as e:
            if warnings is not None:
                warnings.append(f"hook {path.name}: invalid JSON ({e}); skipped")
            continue
        entries = data.get("hooks") if isinstance(data.get("hooks"), list) else [data]
        for h in entries:
            if h.get("enabled") is False:
                continue
            when = h.get("when") or {}
            then = h.get("then") or h.get("action") or {}
            trigger = h.get("trigger") or when.get("type") or ""
            matcher = h.get("matcher")
            if not matcher and when.get("toolTypes"):
                matcher = "|".join(when["toolTypes"])
            action_type = norm(then.get("type") or "command")
            hooks.append({
                "name": h.get("name") or path.stem,
                "source": rel(path, root),
                "description": h.get("description") or "",
                "trigger": trigger,
                "event": KIRO_TRIGGER_TO_CLAUDE.get(norm(trigger)),
                "file_trigger": norm(trigger) in FILE_TRIGGERS and norm(trigger),
                "matcher": matcher,
                "patterns": when.get("patterns") or h.get("patterns") or [],
                "command": then.get("command") if action_type in ("command", "runcommand") else None,
                "prompt": then.get("prompt") if action_type in ("askagent", "prompt") else None,
                "timeout": then.get("timeout", h.get("timeout")),
            })
    return hooks


# --------------------------------------------------------------------------
# Building the output plan
# --------------------------------------------------------------------------

def map_tools(kiro_tools: list, agent: str, warnings: list):
    claude, grant_all = [], False
    for t in kiro_tools:
        key = t if t in KIRO_TOOLS_TO_CLAUDE else t.lower()
        if key.startswith("@") and key not in KIRO_TOOLS_TO_CLAUDE:
            key = "@mcp"  # a specific MCP server
        mapped = KIRO_TOOLS_TO_CLAUDE.get(key, "unknown")
        if mapped == "unknown":
            warnings.append(f"agent {agent}: Kiro tool `{t}` has no Claude Code equivalent; not granted")
        elif mapped is None:
            grant_all = True
        else:
            claude.extend(x for x in mapped if x not in claude)
    return None if grant_all else claude


def map_model(model):
    if not isinstance(model, str):
        return None
    for alias in ("opus", "sonnet", "haiku"):
        if alias in model.lower():
            return alias
    return None


def agent_markdown(agent: dict, skill_names: dict, always_loaded: set, warnings: list) -> str:
    tools = map_tools(agent["tools"], agent["name"], warnings)
    fm = ["---", f"name: {agent['name']}", f"description: {yaml_str(agent['description'] or agent['name'])}"]
    if tools is not None:
        fm.append(f"tools: {', '.join(tools)}")
    model = map_model(agent["model"])
    if model:
        fm.append(f"model: {model}")
    fm.append("---")
    parts = ["\n".join(fm), f"<!-- {GENERATED_NOTE} Source: {agent['source']} -->"]
    if COORDINATOR_TOOLS & {t.lower() for t in agent["tools"]}:
        parts.append(
            "> **Claude Code note:** subagents cannot start other subagents. Run this "
            "agent's workflow in the main session (not as a subagent) and delegate to "
            "the other agents with the Agent tool, using their names as `subagent_type`."
        )
    parts.append(agent["prompt"].strip())
    # Mirror Kiro: `file://` resources are read up front, `skill://` ones on
    # demand. Always-on steering is skipped because CLAUDE.md already loads it.
    loaded = [f for f in agent["files"] if f in always_loaded]
    refs = [f for f in agent["files"] if f not in always_loaded]
    if agent["files"] or agent["skills"]:
        ctx = ["## Context (Kiro `resources`)"]
        if loaded:
            ctx += ["", "The project steering is already in your context (loaded through CLAUDE.md); "
                    "do not read those files again."]
        if agent["skills"]:
            ctx += ["", "Skills: read the SKILL.md when your task needs it."]
            for sk in agent["skills"]:
                folder = Path(sk).parent.name
                renamed = skill_names.get(folder)
                hint = f" (Claude Code skill `{renamed}`)" if renamed and renamed != folder else ""
                ctx.append(f"- `{sk}`{hint}")
        if refs:
            ctx += ["", "Read these before starting:"]
            ctx += [f"- `{f}`" for f in refs]
        parts.append("\n".join(ctx))
    return "\n\n".join(parts).rstrip() + "\n"


def replace_file_refs(body: str) -> str:
    return re.sub(r"#\[\[file:([^\]]+)\]\]", r"`\1` (read this file)", body)


def build_plan(root: Path, warnings: list):
    """Return (outputs, summary): outputs maps path -> (kind, payload)."""
    outputs: dict = {}
    summary = {"agents": [], "coordinators": [], "skills": [], "steering": [], "hooks": [], "unmapped_hooks": []}

    # Skills: symlink the whole folder; rewrite SKILL.md only if renamed.
    skill_names = {}
    for s in read_skills(root):
        name = s["name"]
        if name in RESERVED_SKILL_NAMES:
            new = RENAMED_SKILL_PREFIX + name
            warnings.append(f"skill {name}: shadows a Claude Code built-in; available as `{new}`")
            dest = f".claude/skills/{new}"
            meta_text = (s["dir"] / "SKILL.md").read_text()
            outputs[f"{dest}/SKILL.md"] = ("file", re.sub(
                r"^(name:\s*).*$", rf"\g<1>{new}", meta_text, count=1, flags=re.M))
            for child in sorted(s["dir"].iterdir()):
                if child.name != "SKILL.md":
                    outputs[f"{dest}/{child.name}"] = ("symlink", rel(child, root))
            name = new
        else:
            outputs[f".claude/skills/{name}"] = ("symlink", rel(s["dir"], root))
        skill_names[s["dir"].name] = name
        summary["skills"].append((name, s["description"]))

    # Steering, by Kiro inclusion mode.
    for st in read_steering(root):
        mode = st["inclusion"]
        if mode == "filematch" and st["patterns"]:
            fm = ["---", "paths:"] + [f"  - {yaml_str(p)}" for p in st["patterns"]] + ["---"]
            outputs[f".claude/rules/{st['slug']}.md"] = ("file", "\n".join(fm) + "\n"
                f"<!-- {GENERATED_NOTE} Source: {st['path']} -->\n\n" + replace_file_refs(st["body"]).lstrip())
        elif mode in ("manual", "auto"):
            name = f"steering-{st['slug']}"
            fm = ["---", f"name: {name}", f"description: {yaml_str(st['description'])}"]
            if mode == "manual":
                fm.append("disable-model-invocation: true")
            fm.append("---")
            outputs[f".claude/skills/{name}/SKILL.md"] = ("file", "\n".join(fm) + "\n"
                f"<!-- {GENERATED_NOTE} Source: {st['path']} -->\n\n" + replace_file_refs(st["body"]).lstrip())
        else:
            if mode not in ("always", "filematch"):
                warnings.append(f"steering {st['path']}: unknown inclusion `{mode}`; treated as always")
            if mode == "filematch":
                warnings.append(f"steering {st['path']}: fileMatch without a pattern; treated as always")
            mode = "always"
        summary["steering"].append((st, mode))

    # Agents (after steering: CLAUDE.md already loads always-on steering).
    always_loaded = set()
    for st, mode in summary["steering"]:
        if mode == "always":
            always_loaded |= {st["path"], *(r.strip() for r in st["refs"])}
    for a in read_agents(root, warnings):
        outputs[f".claude/agents/{a['name']}.md"] = ("file", agent_markdown(a, skill_names, always_loaded, warnings))
        summary["agents"].append((a["name"], a["description"]))
        if COORDINATOR_TOOLS & {t.lower() for t in a["tools"]}:
            summary["coordinators"].append(a["name"])

    # Hooks are dispatched live; CLAUDE.md only documents them.
    for h in read_hooks(root, warnings):
        if h["event"] and (h["command"] or h["prompt"]):
            summary["hooks"].append(h)
        else:
            summary["unmapped_hooks"].append(h)

    # MCP servers.
    mcp_src = root / ".kiro/settings/mcp.json"
    if mcp_src.exists():
        try:
            servers = json.loads(mcp_src.read_text()).get("mcpServers", {})
            out = {}
            for name, cfg in servers.items():
                if cfg.get("disabled"):
                    continue
                c = {k: v for k, v in cfg.items() if k in ("command", "args", "env", "url", "headers", "type")}
                if "url" in c and "type" not in c:
                    c["type"] = "http"
                out[name] = json.loads(re.sub(r"\$\{env:([A-Za-z_][A-Za-z0-9_]*)\}", r"${\1}", json.dumps(c)))
            outputs[".mcp.json"] = ("file", json.dumps({"mcpServers": out}, indent=2) + "\n")
        except ValueError as e:
            warnings.append(f".kiro/settings/mcp.json: invalid JSON ({e}); skipped")

    # CLAUDE.md (or a side file when the project has a hand-written CLAUDE.md).
    if claude_md_is_unmanaged(root):
        md_path = ".claude/kiro2claude.md"
        warnings.append("CLAUDE.md is hand-written; generated instructions written to "
                        f"{md_path}. Add the line `@{md_path}` to CLAUDE.md to load them.")
    else:
        md_path = "CLAUDE.md"
    outputs[md_path] = ("file", claude_md(root, md_path, summary))
    return outputs, summary


def claude_md(root: Path, md_path: str, summary: dict) -> str:
    md_dir = (root / md_path).parent

    def imp(p: str) -> str:
        return "@" + os.path.relpath(root / p, md_dir).replace(os.sep, "/")

    out = [f"<!-- {GENERATED_NOTE} -->", "", "# Project AI workflow (from Kiro)", "",
           "This project's AI workflow lives in `.kiro/` and is shared with Kiro. "
           "This file and the agents, skills and rules under `.claude/` are generated from it; "
           "to change behaviour, edit `.kiro/`."]

    always = [st for st, mode in summary["steering"] if mode == "always"]
    if always:
        out += ["", "## Steering (always applies)", ""]
        for st in always:
            out.append(imp(st["path"]))
            out += [imp(r.strip()) for r in st["refs"]]
    scoped = [st for st, mode in summary["steering"] if mode == "filematch"]
    if scoped:
        out += ["", "## Path-scoped steering", "",
                "Loaded from `.claude/rules/` when you work on matching files:"]
        out += [f"- `{st['path']}`: {', '.join(f'`{p}`' for p in st['patterns'])}" for st in scoped]
    on_demand = [(st, mode) for st, mode in summary["steering"] if mode in ("manual", "auto")]
    if on_demand:
        out += ["", "## On-demand steering", ""]
        out += [f"- `steering-{st['slug']}` ({'invoke with /' + 'steering-' + st['slug'] if mode == 'manual' else 'loaded when relevant'}): `{st['path']}`"
                for st, mode in on_demand]

    specs = root / ".kiro/specs"
    if specs.is_dir():
        spec_dirs = sorted(p for p in specs.iterdir() if p.is_dir())
        if spec_dirs:
            out += ["", "## Specs", ""]
            for d in spec_dirs:
                files = ", ".join(f"`{p.name}`" for p in sorted(d.glob("*.md")))
                out.append(f"- `{rel(d, root)}/`: {files}")

    if summary["agents"]:
        out += ["", "## Agents", "",
                "Defined in `.kiro/agents/`, available as Claude Code subagents (`.claude/agents/`):"]
        out += [f"- `{n}`: {first_sentence(d)}" for n, d in summary["agents"]]
        if summary["coordinators"]:
            names = ", ".join(f"`{n}`" for n in summary["coordinators"])
            out += ["", f"Coordinator agents ({names}) delegate to the others. Subagents cannot start "
                    "subagents in Claude Code, so to use a coordinator the main session reads its file in "
                    "`.claude/agents/` and follows it, delegating with the Agent tool."]

    if summary["skills"]:
        out += ["", "## Skills", "", "From `.kiro/skills/`, loaded when relevant:"]
        out += [f"- `{n}`" for n, _ in summary["skills"]]

    if summary["hooks"] or summary["unmapped_hooks"]:
        out += ["", "## Hooks", ""]
        if summary["hooks"]:
            out.append("Kiro hooks in `.kiro/hooks/` run automatically in Claude Code:")
            for h in summary["hooks"]:
                m = f", matcher `{h['matcher']}`" if h["matcher"] else ""
                out.append(f"- `{h['name']}`: {h['event']}{m}")
        if summary["unmapped_hooks"]:
            out += ["", "These Kiro hooks have no Claude Code trigger. Do what they do yourself at the right moment:"]
            for h in summary["unmapped_hooks"]:
                what = f"run `{h['command']}`" if h["command"] else f"follow: {h['prompt']}" if h["prompt"] else "see its definition"
                desc = f" {first_sentence(h['description'], 300)}" if h["description"] else ""
                out.append(f"- `{h['name']}` (Kiro trigger `{h['trigger']}`): {what}.{desc}")
    return "\n".join(out) + "\n"


# --------------------------------------------------------------------------
# Writing outputs
# --------------------------------------------------------------------------

def _matches(path: Path, kind: str, payload: str, root: Path) -> bool:
    if kind == "symlink":
        return path.is_symlink() and os.path.realpath(path) == os.path.realpath(root / payload)
    if kind == "tree":
        return path.is_dir() and not path.is_symlink()
    return path.is_file() and not path.is_symlink() and path.read_text() == payload


def _remove(path: Path) -> None:
    if path.is_symlink() or path.is_file():
        path.unlink()
    elif path.is_dir():
        shutil.rmtree(path)


def _prune_empty_dirs(path: Path, root: Path) -> None:
    stop = root / ".claude"
    p = path.parent
    while p != stop and p != root and stop in p.parents:
        try:
            p.rmdir()
        except OSError:
            return
        p = p.parent


def apply_plan(root: Path, outputs: dict, old_outputs: dict, warnings: list) -> dict:
    """Write outputs and remove stale ones we own.

    Returns ({path: kind} now owned, {"added"|"updated"|"removed": [paths]}).
    """
    changes = {"added": [], "updated": [], "removed": []}
    written = {}
    for relpath, (kind, payload) in sorted(outputs.items()):
        path = root / relpath
        exists = path.exists() or path.is_symlink()
        if exists and _matches(path, kind, payload, root):
            written[relpath] = kind
            continue
        if exists and relpath not in old_outputs:
            warnings.append(f"{relpath}: exists and was not created by {TOOL}; left untouched")
            continue
        if exists:
            _remove(path)
        path.parent.mkdir(parents=True, exist_ok=True)
        if kind == "symlink":
            try:
                os.symlink(os.path.relpath(root / payload, path.parent), path)
            except OSError:  # e.g. Windows without symlink rights: copy instead
                src = root / payload
                shutil.copytree(src, path) if src.is_dir() else shutil.copy2(src, path)
                kind = "tree" if src.is_dir() else "file"
        else:
            path.write_text(payload)
        written[relpath] = kind
        changes["updated" if exists else "added"].append(relpath)
    for relpath in sorted(set(old_outputs) - set(outputs)):
        path = root / relpath
        if path.exists() or path.is_symlink():
            _remove(path)
            _prune_empty_dirs(path, root)
        changes["removed"].append(relpath)
    return written, changes


def outputs_present(root: Path, state: dict) -> bool:
    return all((root / o["path"]).exists() for o in state.get("outputs", []))


def sync(root: Path, force: bool = False, check: bool = False):
    """Returns (status, changes, warnings); status is 'current' or 'synced'."""
    digest = compute_hash(root)
    state = load_state(root)
    if not force and state.get("hash") == digest and outputs_present(root, state):
        return "current", None, state.get("warnings", [])
    if check:
        return "stale", None, []
    warnings: list = []
    outputs, _ = build_plan(root, warnings)
    old = {o["path"]: o["kind"] for o in state.get("outputs", [])}
    written, changes = apply_plan(root, outputs, old, warnings)
    (root / STATE_DIR).mkdir(parents=True, exist_ok=True)
    state = {
        "hash": digest,
        "outputs": [{"path": p, "kind": k} for p, k in sorted(written.items())],
        "warnings": warnings,
    }
    (root / STATE_FILE).write_text(json.dumps(state, indent=2) + "\n")
    return "synced", changes, warnings


def format_report(changes: dict, warnings: list) -> str:
    lines = []
    for key in ("added", "updated", "removed"):
        if changes and changes[key]:
            lines.append(f"{key}: {', '.join(changes[key])}")
    lines += [f"warning: {w}" for w in warnings]
    return "\n".join(lines)


def cmd_sync(args: list) -> int:
    root = find_root()
    session = "--session-start" in args
    try:
        status, changes, warnings = sync(root, force="--force" in args, check="--check" in args)
    except Exception as e:  # never break a session over a sync problem
        msg = f"{TOOL}: sync failed: {e}"
        if session:
            print(json.dumps({"systemMessage": msg}))
            return 0
        print(msg, file=sys.stderr)
        return 1
    if status == "stale":
        print(f"{TOOL}: generated files are out of date; run `sync`", file=sys.stderr)
        return 1
    if session:
        if status == "synced":
            report = format_report(changes, warnings)
            context = (
                f"{TOOL} regenerated the Claude Code setup from .kiro/ at session start.\n{report}\n"
                "Files written now may not be loaded in this session yet: read CLAUDE.md before "
                "starting work. New or changed agents load after a restart."
            )
            print(json.dumps({
                "systemMessage": f"{TOOL}: regenerated Claude Code setup from .kiro/ "
                                 f"({sum(len(v) for v in changes.values())} changes). Restart to load new agents.",
                "hookSpecificOutput": {"hookEventName": "SessionStart", "additionalContext": context},
            }))
        return 0
    if status == "current":
        print(f"{TOOL}: up to date")
    else:
        print(f"{TOOL}: synced")
        report = format_report(changes, warnings)
        if report:
            print(report)
    return 0


# --------------------------------------------------------------------------
# Hook dispatch
# --------------------------------------------------------------------------

def _tool_aliases(tool_name: str) -> set:
    aliases = {tool_name} | CLAUDE_TOOL_TO_KIRO.get(tool_name, set())
    m = re.match(r"^mcp__(.+?)__(.+)$", tool_name or "")
    if m:
        aliases |= {"@mcp", f"@{m.group(1)}", f"@{m.group(1)}/{m.group(2)}"}
    return aliases


def _matcher_hits(matcher, tool_name: str) -> bool:
    if not matcher or matcher.strip() in ("*", ".*"):
        return True
    aliases = _tool_aliases(tool_name)
    try:
        rx = re.compile(f"^(?:{matcher})$")
        return any(rx.match(a) for a in aliases)
    except re.error:
        return matcher in aliases


def _path_hits(patterns: list, file_path: str, root: Path) -> bool:
    if not patterns:
        return True
    try:
        relpath = Path(file_path).resolve().relative_to(root).as_posix()
    except ValueError:
        relpath = file_path
    for p in patterns:
        if fnmatch.fnmatch(relpath, p) or (p.startswith("**/") and fnmatch.fnmatch(relpath, p[3:])):
            return True
    return False


def hook_applies(h: dict, event: str, payload: dict, root: Path) -> bool:
    if h["event"] != event:
        return False
    tool = payload.get("tool_name", "")
    if h["file_trigger"]:
        if tool not in FILE_WRITE_TOOLS or (h["file_trigger"] == "filecreated" and tool != "Write"):
            return False
        ti = payload.get("tool_input") or {}
        return _path_hits(h["patterns"], ti.get("file_path") or ti.get("notebook_path") or "", root)
    if event in ("PreToolUse", "PostToolUse"):
        return _matcher_hits(h["matcher"], tool)
    return True


def cmd_dispatch(args: list) -> int:
    if not args:
        print(f"usage: {TOOL} dispatch <ClaudeHookEvent>", file=sys.stderr)
        return 1
    event = args[0]
    root = find_root()
    raw = sys.stdin.read()
    try:
        payload = json.loads(raw) if raw.strip() else {}
    except ValueError:
        payload = {}

    contexts, extra, failures = [], {}, []
    for h in read_hooks(root):
        if not hook_applies(h, event, payload, root):
            continue
        if h["prompt"]:
            if event == "Stop":
                if not payload.get("stop_hook_active"):
                    extra.update({"decision": "block", "reason": h["prompt"]})
            else:
                contexts.append(h["prompt"])
            continue
        if not h["command"]:
            continue
        timeout = h["timeout"] if isinstance(h["timeout"], (int, float)) and h["timeout"] > 0 else None
        try:
            proc = subprocess.run(h["command"], shell=True, cwd=root, input=raw, text=True,
                                  capture_output=True, timeout=timeout)
        except subprocess.TimeoutExpired:
            failures.append(f"{h['name']}: timed out after {timeout}s")
            continue
        if proc.returncode == 2:  # blocking, in both Kiro and Claude Code
            sys.stderr.write(proc.stderr or f"{h['name']}: blocked\n")
            return 2
        if proc.returncode != 0:
            failures.append(f"{h['name']}: exit {proc.returncode}: {proc.stderr.strip()}")
        out = proc.stdout.strip()
        if out:
            try:
                parsed = json.loads(out)
            except ValueError:
                parsed = None
            if isinstance(parsed, dict):
                extra.update(parsed)
            else:
                contexts.append(out)

    if contexts:
        if event in ("SessionStart", "UserPromptSubmit", "PostToolUse"):
            hso = extra.setdefault("hookSpecificOutput", {"hookEventName": event})
            prev = hso.get("additionalContext")
            hso["additionalContext"] = "\n\n".join(([prev] if prev else []) + contexts)
        else:
            sys.stderr.write("\n".join(contexts) + "\n")
    if extra:
        print(json.dumps(extra))
    if failures:
        sys.stderr.write("\n".join(failures) + "\n")
        return 1
    return 0


# --------------------------------------------------------------------------
# init
# --------------------------------------------------------------------------

NOT_INSTALLED_NOTICE = json.dumps({"systemMessage": (
    f"{TOOL} is not installed, so this project's .kiro/ workflow is not loaded in "
    f"Claude Code. Install it as described in the {TOOL} README.")})


def settings_json(root: Path, script=None) -> dict:
    """Hooks for .claude/settings.json.

    A copy of this file inside the project (vendored) is run by path; otherwise
    the installed `kiro2claude` command is used. Either way a missing tool is
    skipped (exit 0): a failed command could exit 2, which Claude Code treats
    as "block this tool call".
    """
    script = Path(script or __file__).resolve()
    try:
        vendored = script.relative_to(root.resolve()).as_posix()
    except ValueError:
        vendored = None
    hooks = {}
    for event, timeout in DISPATCHED_EVENTS.items():
        entries = []
        for args in (["sync --session-start"] if event == "SessionStart" else []) + [f"dispatch {event}"]:
            notice = f"echo {shlex.quote(NOT_INSTALLED_NOTICE)}; " if args.startswith("sync") else ""
            if vendored:
                cmd = (f'f="$CLAUDE_PROJECT_DIR/{vendored}"; [ -f "$f" ] || {{ {notice}exit 0; }}; '
                       f'python3 "$f" {args}')
            else:
                cmd = f"command -v {TOOL} >/dev/null 2>&1 || {{ {notice}exit 0; }}; {TOOL} {args}"
            entries.append({"type": "command", "command": cmd, "timeout": timeout})
        hooks[event] = [{"hooks": entries}]
    return {"hooks": hooks}


def cmd_init(args: list) -> int:
    root = find_root()
    settings = root / ".claude/settings.json"
    wanted = settings_json(root)
    if settings.exists() and "--force" not in args:
        try:
            current = json.loads(settings.read_text())
        except ValueError:
            current = None
        if current != wanted:
            print(f"{TOOL}: .claude/settings.json exists; merge these hooks into it "
                  "(or rerun with --force to overwrite):", file=sys.stderr)
            print(json.dumps(wanted, indent=2))
            return 1
    settings.parent.mkdir(parents=True, exist_ok=True)
    settings.write_text(json.dumps(wanted, indent=2) + "\n")
    gitignore = root / ".gitignore"
    text = gitignore.read_text() if gitignore.exists() else ""
    if GITIGNORE_BLOCK.splitlines()[0] not in text:
        gitignore.write_text(text + ("\n" if text and not text.endswith("\n\n") else "") + GITIGNORE_BLOCK)
    print(f"{TOOL}: wrote .claude/settings.json and .gitignore entries")
    return cmd_sync(["--force"])


def main(argv: list) -> int:
    commands = {"sync": cmd_sync, "dispatch": cmd_dispatch, "init": cmd_init}
    if argv[:1] == ["--version"]:
        print(f"{TOOL} {__version__}")
        return 0
    if not argv or argv[0] not in commands:
        print(__doc__, file=sys.stderr)
        return 1
    return commands[argv[0]](argv[1:])


def cli() -> None:
    """Console-script entry point."""
    sys.exit(main(sys.argv[1:]))


if __name__ == "__main__":
    cli()
